feat: add new pre-commit hook: validate ibm_catalog.json inputs
terraform-ibm-modules/common-dev-assets pull request #1080
Opened 2024-12-16 20:43 UTC by akocbek

### Description

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-12-16 20:43 UTC, akocbek commented
<img width="1146" alt="image" src="https://github.com/user-attachments/assets/afb0f80e-679d-42e9-bb47-8a86c53af2e5" />

2024-12-18 14:49 UTC, ocofaigh commented on module-assets/ci/validateIbmCatalogJson.py
> +DA_FOLDER = "solutions"
not all DAs will be in a solutions folder. The working directory of the DA will be in the ibm_catalog.json. And if its not, it means it defaults to the root directory of the repo.

2024-12-18 14:52 UTC, ocofaigh commented on module-assets/ci/validateIbmCatalogJson.py
> +    if ibm_catalog and "products" in ibm_catalog and ibm_catalog["products"]:
can you make sure we only do this for `"product_kind": "solution",` ?

2024-12-18 14:54 UTC, ocofaigh requested changes
see initial comments

2025-01-14 11:30 UTC, ocofaigh approved these changes

2025-01-14 11:30 UTC, merged