doc: Add documentation how to update template module code
terraform-ibm-modules/common-dev-assets pull request #158
Opened 2022-09-16 11:05 UTC by akocbek

### Description

Please include a summary of the change and which issue is fixed. Also, please include the motivation and context for the change. List any dependencies that are required for this change.

**Check the relevant boxes:**
- [ ] Bug fix (nonbreaking change that fixes an issue)
- [ ] New feature (nonbreaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI related update (pipeline, etc.)

### Checklist

- [ ] If relevant, a test for the change has been added or updated as part of this PR.
- [ ] If relevant, documentation for the change has been added or updated as part of this PR.

### Merge

- Merge using "Squash and merge".
- Make sure to use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents. The commit message determines whether a new version of the modules needs to be released, and if so, which semver number to use).

2022-09-16 19:31 UTC, SirSpidey requested changes
Stylistic changes. I don't think I changed the accuracy, but make sure.

2022-09-16 19:31 UTC, SirSpidey commented on module-assets/ci/module-template-automation/README.md
> +Most of the code for `template module` is stored in [common-dev-assets](https://github.com/terraform-ibm-modules/common-dev-assets). Therefore, to make any code changes to `template module`, files in
```suggestion
# Updating the module template readme file content
Most of the code for the readme file in the `terraform-ibm-module-template` repo is stored in [common-dev-assets](https://github.com/terraform-ibm-modules/common-dev-assets). To make changes to the readme file, update the files in this directory.
```

2022-09-16 19:31 UTC, SirSpidey commented on module-assets/ci/module-template-automation/README.md
> +- [Modifying tests README file](.terraform-docs-config-template-module-tests.yaml)
```suggestion
To modify the Markdown content, change the following files:
- To modify most content in the main readme file, update [.terraform-docs-config-template-module.yaml](.terraform-docs-config-template-module.yaml).

    To modify the contributing section of of the main readme file, update [.terraform-docs-config-template-module-contribution.yaml](.terraform-docs-config-template-module-contribution.yaml).
- To modify the readme file in the `tests` directory, update [.terraform-docs-config-template-module-tests.yaml](.terraform-docs-config-template-module-tests.yaml).
```

2022-09-16 19:31 UTC, SirSpidey commented on module-assets/ci/module-template-automation/README.md
> +To update `tests` the code inside [tests](tests) should be changed.
```suggestion
To update the default examples for the module template, update the code in the [examples](examples) directory in this rep.

To update the default tests, update the files in the [tests](tests) directory in this repo.
```

2022-09-16 19:31 UTC, SirSpidey commented on module-assets/ci/module-template-automation/README.md
> +- creates markdown (README) files
```suggestion
The [build_module_template](../../.pre-commit-config.yaml) pre-commit hook assembles the content for the module template repo. The hook runs the following actions:
- Copies the code, examples, and tests from this `common-dev-assets` repo to the `terraform-ibm-module-template` repo.
- Creates the readme files in the `terraform-ibm-module-template` repo.
```

2022-09-19 07:40 UTC, akocbek commented
@SirSpidey I addressed your comments. Since this doc concerns both private and public module template repos. Therefore I used: `module-template` or `terraform-ibm-module-template`
an example
```
Most of the code for the readme file in the `module-template` or `terraform-ibm-module-template` repo is stored in [common-dev-assets](https://github.com/terraform-ibm-modules/common-dev-assets)....
```

2022-09-19 13:39 UTC, SirSpidey approved these changes
👍 Thanks for the updates.

2022-09-19 14:03 UTC, SirSpidey commented
@ocofaigh All set to merge

2022-09-19 14:50 UTC, merged