feat: use ibm provider for module-metadata generator
terraform-ibm-modules/common-dev-assets pull request #197
Opened 2022-10-25 09:03 UTC by akocbek

### Description

Generate metadata-module.json using ibm provider

**Check the relevant boxes:**
- [ ] Bug fix (nonbreaking change that fixes an issue)
- [ ] New feature (nonbreaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI related update (pipeline, etc.)

### Checklist

- [ ] If relevant, a test for the change has been added or updated as part of this PR.
- [ ] If relevant, documentation for the change has been added or updated as part of this PR.

### Merge

- Merge using "Squash and merge".
- Make sure to use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents. The commit message determines whether a new version of the modules needs to be released, and if so, which semver number to use).

2022-10-25 09:56 UTC, ocofaigh commented on module-assets/.pre-commit-config.yaml
> -      entry: ci/terraform-config-inspect.sh
This file can be deleted now right?

2022-10-25 10:10 UTC, ocofaigh requested changes
There is a use case we may want to cover here. If a local cache (.terraform) folder already exists but it is out of date. In which case an old version of provider may accidentally be used.
We could have our script always run `terraform init` (it won't do anything if the cache is up to date, and it will try to update it if it is out of date) however if an error occurs we should have the automation handle it and attempt to run `terraform iniy -upgrade` which will forcefully overwrite the cache with the correct versions.

Here is one use case I just tried:
1. ran `terraform init` locally which created .terraform folder
2. updated the required provider version in my code
3. ran `terraform init` again. It failed with:
```
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider ibm-cloud/ibm: locked provider registry.terraform.io/ibm-cloud/ibm 1.45.0 does not match configured version constraint >=
│ 1.41.1, >= 1.44.3, >= 1.45.0, 1.45.1; must use terraform init -upgrade to allow selection of new versions
```
4. ran `terraform init -upgrade` and it passed

2022-10-25 14:05 UTC, akocbek commented on module-assets/.pre-commit-config.yaml
> -      entry: ci/terraform-config-inspect.sh
deleted

2022-10-25 14:12 UTC, ocofaigh commented on module-assets/ci/terraformConfigInspect.py
> +    os.system("terraform init -upgrade")
I don’t want to run `terraform init -upgrade` every time because it will take longer as it will always pull, even when we dont need to. So can we only run if `terraform init` fails?

2022-10-25 14:13 UTC, ocofaigh commented
@akocbek See https://github.com/terraform-ibm-modules/common-dev-assets/pull/197/files#r1004544953

2022-10-26 09:57 UTC, ocofaigh approved these changes

2022-10-26 09:57 UTC, merged