feat: integration with logdna-agent
terraform-ibm-modules/common-dev-assets pull request #301
Opened 2022-12-17 01:46 UTC by imprateeksh

### Description

logdna-agent integration has been done to validate checks in various pipelines and capture PR numbers along with repository names.

**Check the relevant boxes:**
- [ ] Bug fix (nonbreaking change that fixes an issue)
- [x] New feature (nonbreaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [x] CI related update (pipeline, etc.)

### Checklist

- [ ] If relevant, a test for the change has been added or updated as part of this PR.
- [ ] If relevant, documentation for the change has been added or updated as part of this PR.

### Merge

- Merge using "Squash and merge".
- Make sure to use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents. The commit message determines whether a new version of the modules needs to be released, and if so, which semver number to use).

2022-12-18 13:10 UTC, ocofaigh commented on module-assets/ci/run-tests.sh
> +      export MZ_TAGS=$REPO_NAME,"PR $PR_NUM"
maybe remove the space so the PR number is all one word - `"PR$PR_NUM"`

2022-12-18 13:11 UTC, ocofaigh requested changes
One small comment, and I think we are the good

2022-12-19 09:20 UTC, imprateeksh commented on module-assets/ci/run-tests.sh
> +      export MZ_TAGS=$REPO_NAME,"PR $PR_NUM"
Sure. made the change.

2022-12-19 09:34 UTC, imprateeksh commented
> One small comment, and I think we are the good

@ocofaigh I have made the change as mentioned.

2022-12-19 10:45 UTC, ocofaigh approved these changes

2022-12-19 10:45 UTC, merged