feat: added pre-commit hook to prevent change to apache license file
terraform-ibm-modules/common-dev-assets pull request #397
Opened 2023-01-24 18:17 UTC by kierramarie

### Description

Added a pre-commit hook that allows us to specify files we want to not change or be deleted. It does allow for adding these files.

### Types of changes in this PR

#### No release required

- [ ] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [x] CI-related update (pipeline, etc.)
- [ ] Other changes that don't affect Terraform code

#### Release required

- [ ] Bug fix (patch release (`x.x.X`): Change that fixes an issue and is compatible with earlier versions)
- [x] New feature (minor release (`x.X.x`): Change that adds functionality and is compatible with earlier versions)
- [ ] Breaking change (major release (`X.x.x`): Change that is likely incompatible with previous versions)

##### Release notes content

Added a new pre-commit hook

---

### Checklist for reviewers

- [x] The PR references a GitHub issue.
- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Merge by using "Squash and merge".
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.

    The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).

2023-01-26 21:03 UTC, ocofaigh reviewed
@kierramarie I don't think this is the hook we want. The hook we want is to ensure an apache license exists in the repo, and if its missing, the hook should fail

2023-02-02 10:10 UTC, ocofaigh commented on module-assets/.pre-commit-config.yaml
> +    - id: "check-for-license-hook"
Since the hook is generic, lets rename this to "ensure-file-exists"

2023-02-02 10:11 UTC, ocofaigh commented on module-assets/.pre-commit-config.yaml
> +      entry: ci/check_for_license.sh
rename the scrip to `ensure-file-exists.sh`

2023-02-02 10:18 UTC, ocofaigh commented on module-assets/ci/check_for_license.sh
> +done
This script seems far too complicated. Why do we even need to pass `--NUM_OF_FILES_TO_CHECK` ?
Just pass all of the files to check, loop through them and ensure they exist

It should be as simple as wrapping below logic in a for loop:
```
if [[ ! -f "$filename" ]]; then
  echo "Required file $filename is missing."
  exit 1
fi
```

2023-02-09 19:12 UTC, kierramarie commented
@ocofaigh I used the script Andrej gave me and add the license to all the internal ge repos.

2023-02-15 22:30 UTC, ocofaigh reviewed
Did you test this script against any repo? I just ran it against a repo that has terraform files in it and it with no LICENSE file, and it exited with 0 exit code:

```
+ regex=' [^//]*.tf '
+ [[ ! '' =~  [^//]*.tf  ]]
+ exit 0
```

2023-02-16 16:49 UTC, kierramarie commented
I have a test repo I have been using. I will test it some more.

2023-02-16 16:54 UTC, kierramarie commented
@ocofaigh can you tell me which repo that is failing for? because it works fine with my test repo.

2023-03-08 13:06 UTC, ocofaigh reviewed
Something odd going on with our PR. It seems to include changes that are already in main branch. It says its rebased with main already, so perhaps create a fresh new PR?

2023-03-14 17:06 UTC, ocofaigh requested changes
see comments

2023-03-14 17:06 UTC, ocofaigh commented on module-assets/ci/license_checker.sh
> +    echo "internal repo"
remove the echo - no need to output here

2023-03-14 17:06 UTC, ocofaigh commented on module-metadata.json
> +}
why have you added this file? please remove it

2023-03-16 22:38 UTC, kierramarie commented on module-metadata.json
> +}
I think the pre-commit added it.

2023-03-20 12:32 UTC, ocofaigh commented
@kierramarie I pushed some cleanup code to your PR. Can you test everything works ok? If happy, I think we can merge. Ensure you test on an internal repo, a public repo with tf files and a public repo with tf files. Thanks

2023-03-29 22:50 UTC, kierramarie commented
@ocofaigh tested and it still works just fine. Tested in repos with and without .tf files both internal and external.

2023-03-30 09:54 UTC, ocofaigh approved these changes

2023-03-30 09:54 UTC, merged