update src references
terraform-ibm-modules/common-dev-assets pull request #438
Opened 2023-02-08 03:02 UTC by mounika-nalla

### Description

automation script to update src references for 
GH issue: https://github.ibm.com/GoldenEye/issues/issues/3523 
https://github.ibm.com/GoldenEye/issues/issues/3522

### Types of changes in this PR

#### No release required

- [ ] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI-related update (pipeline, etc.)
- [ ] Other changes that don't affect Terraform code

#### Release required

- [ ] Bug fix (patch release (`x.x.X`): Change that fixes an issue and is compatible with earlier versions)
- [ ] New feature (minor release (`x.X.x`): Change that adds functionality and is compatible with earlier versions)
- [ ] Breaking change (major release (`X.x.x`): Change that is likely incompatible with previous versions)

##### Release notes content

Replace this text with information that users need to know about the bug fixes, features, and breaking changes. This information helps the merger write the commit message that is published in the release notes for the module.

---

### Checklist for reviewers

- [ ] The PR references a GitHub issue.
- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Merge by using "Squash and merge".
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.

    The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).

2023-02-17 15:24 UTC, daniel-butler-irl requested changes
Can we get a readme, with usage documentation? Also needs a `requirements.txt` with the 3rd party deps (git, requests)

2023-02-17 15:26 UTC, daniel-butler-irl commented on scripts/run-update-src.py
> +search_pattern_tim = (
Best practice in Python is to write constant variable names in `ALL_CAPS`

2023-02-17 15:36 UTC, daniel-butler-irl commented on scripts/run-update-src.py
> +
Put inside `if __name__ == "__main__":` as best practice. See https://realpython.com/if-name-main-python/

2023-02-17 15:46 UTC, daniel-butler-irl commented on scripts/run-update-src.py
> +def get_response(repo_name):
Please add type hinting and docstrings to all functions, for an example see https://github.ibm.com/GoldenEye/bootstrap-s3-backend-module/blob/master/scripts/switch_backend.py#L13
https://realpython.com/lessons/type-hinting/
https://realpython.com/documenting-python-code/#docstring-types

2023-02-17 15:55 UTC, daniel-butler-irl commented on scripts/run-update-src.py
> +        if current_file_extension == "**/*.md":
As far as I can tell this block is identical to the if tf block, except the replace_source version_update parameter, is different. Generally, this is an indicator that the code needs to be extracted into a function. However in this case you can update to something similar:
```python
for current_file_extension in files_to_be_searched:
   vesion_update = None
   if current_file_extension == "**/*.md":
      version_update = True
   else if current_file_extension == "**/*.tf":
      version_update = False
   files = []
   store = []
   files, lines = get_files(current_file_extension, search_pattern_tim, [], [])
   # etc....
        data = replace_source(
                        file, search_pattern_ge, replace_text, version_update, store
                    )
   # etc....
   
```

2023-02-17 15:56 UTC, daniel-butler-irl commented on scripts/run-update-src.py
> +    for current_file_extension in files_to_be_searched:
I think a better name for this would be `current_file_pattern` as it better describes the value

2023-02-23 15:33 UTC, ocofaigh requested changes
We may in the future have other scripts that we may wish to add to the scripts folder. Suggest you create another folder within the scripts folder to place all these files in?

2023-02-23 15:57 UTC, daniel-butler-irl requested changes
Ok big improvement, just a few more changes

2023-02-23 15:57 UTC, daniel-butler-irl commented on scripts/run-update-src.py
> +       search_pattern(str): search for GoldenEye or terraform-ibm-modules source links
again the function is not specific to goldeneye or terraform-ibm-modules

2023-02-23 15:57 UTC, daniel-butler-irl commented on scripts/run-update-src.py
> +def extract_repo_name(repo_name: str) -> str:
you could update this to `def extract_repo_name(repo_name: str, prefix="terraform-ibm-":str) ->str` That way its more flexible

2023-02-24 15:13 UTC, daniel-butler-irl approved these changes

2023-02-24 15:15 UTC, merged