[Do Not Merge] fix : added test samples for fixing lint issues.
terraform-ibm-modules/common-dev-assets pull request #909
Opened 2024-02-21 20:03 UTC by imprateeksh

### Description
The change is to include some dummy code for terraform, a docker file and go lang program to ensure the checks are not skipped in pipeline runs.
Refer [Issue-6845](https://github.ibm.com/goldeneye/issues/issues/6845)

### Release required?

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-02-22 04:11 UTC, imprateeksh commented
Docker and Go has passed. Working on resolving the below skipped/failed steps:
- terraform partial skip messages i.e. `Terraform validate` and `Terraform validate with trivy`
- terragrunt checks

<img width="1106" alt="image" src="https://github.com/terraform-ibm-modules/common-dev-assets/assets/78964991/12ca1f50-d29f-46b6-8907-5b0ec240aaa6">

2024-02-22 09:00 UTC, ocofaigh commented
@imprateeksh Pull the latest git submodule into this Pr and retry: `git submodule update --remote --merge`

2024-02-22 09:02 UTC, ocofaigh commented
@imprateeksh Ahh I see whats wrong - we need to update the pipeline to install dependencies - let me push an update now ..

2024-02-22 09:09 UTC, ocofaigh commented
We no longer use terragrunt, so I think we can remove the pre commit hook from our yaml file

2024-02-22 09:17 UTC, ocofaigh commented
@imprateeksh Terraform validate is skipped because the hook is actually set up to only scan for `files: ^examples/|^patterns/|^solutions/`

I have a GIT issue in our backlog to see if we can find a way to "opt in" to more directories. The reason we don't scan all files is because the hook will not work on a module that does not have a `provider.tf` file in (aka a module). For now, perhaps add the tf code to an `examples` directory?

2024-02-22 09:17 UTC, imprateeksh commented
Thanks @ocofaigh It passes now. 

<img width="646" alt="image" src="https://github.com/terraform-ibm-modules/common-dev-assets/assets/78964991/8badd7e6-75ee-4bca-9eb6-6e91f6cb4026">

2024-02-22 10:01 UTC, ocofaigh requested changes
can you move the tf code into a sub directory in examples (maybe `examples/mock-tf-code`)? And then add a README.md with a description saying the code in the directory is used for testing pre-commit hooks.

The following hook is still skipped:
`Add module repository to go.mod......................(no files to check)Skipped`

To address it, can you rename `test` directory to `tests` and add a go.mod file please?

2024-02-22 11:11 UTC, imprateeksh commented on .github/workflows/ci.yml
> +          TFSWITCH_DIRECTORY: "test/example_tf"
sure. Thank you Conall. I have made the changes and modified `TFSWITCH_DIRECTORY`

2024-02-22 11:13 UTC, imprateeksh commented
<img width="584" alt="image" src="https://github.com/terraform-ibm-modules/common-dev-assets/assets/78964991/fef4c819-1d6a-4473-868b-d45c1b3151bd">

2024-02-22 11:22 UTC, ocofaigh commented
@imprateeksh The code in the go.mod hook won't be tested unless you add a go.mod file in a directory called `tests` - please add the go code into there

2024-02-22 11:34 UTC, imprateeksh commented
> @imprateeksh The code in the go.mod hook won't be tested unless you add a go.mod file in a directory called `tests` - please add the go code into there. Same with go linter - its only currently setup to check golang code in a `tests` directory

I have added `tests` inside `examples` directory. It has passed the checks too. Do you suggest to move the `tests` outside?
<img width="364" alt="image" src="https://github.com/terraform-ibm-modules/common-dev-assets/assets/78964991/554e9746-0178-4818-8ef0-cc05c657b677">

2024-02-22 11:49 UTC, ocofaigh commented
@imprateeksh Are you sure the hooks are working on those files though? Try locally, but looking at the logic in the scripts that the hooks use, I think they only run if files found in `tests` directory. The hook will still be marked as PASS because the script does run but the logic inside the script doesn't do anything. We want to test the script logic here.

2024-02-22 12:59 UTC, imprateeksh commented
> @imprateeksh Are you sure the hooks are working on those files though? Try locally, but looking at the logic in the scripts that the hooks use, I think they only run if files found in `tests` directory. The hook will still be marked as PASS because the script does run but the logic inside the script doesn't do anything. We want to test the script logic here.

Confirmed that the script's execution logic is functioning correctly after moving `tests` directory to the root folder.

2024-02-22 21:24 UTC, ocofaigh commented on tests/go.mod
> +module sample.go
Hmm, if the hook was working, it would actually update this to `module github.ibm.com/GoldenEye/operations`

2024-02-26 08:35 UTC, imprateeksh commented on tests/go.mod
> +module sample.go
@ocofaigh - Please suggest if my understanding is not correct here.

If you are referring to the `terraformDocGoMod.py` file that modifies the `go.mod` file then I think it requires name `module` to be followed by `github` for the above suggested update to occur.

<img width="958" alt="image" src="https://github.com/terraform-ibm-modules/common-dev-assets/assets/78964991/57eb832b-bbb9-470c-8058-801069d33388">

**Now, I simply provided `github` after module:** 

<img width="882" alt="image" src="https://github.com/terraform-ibm-modules/common-dev-assets/assets/78964991/e5fd3221-e61c-4f7e-9f17-e9fdaf7fa001">

**This got changed immediately on running pre-commit hook:** 

<img width="1255" alt="image" src="https://github.com/terraform-ibm-modules/common-dev-assets/assets/78964991/63b18a00-8466-412b-b6f7-2dab1b4e4515">

2024-02-26 10:49 UTC, ocofaigh commented on tests/go.mod
> +module sample.go
@imprateeksh ok yes, so can you please add the github url so the code executes

2024-02-26 17:59 UTC, ocofaigh approved these changes

2024-02-26 17:59 UTC, merged