feat: add pre-commit hook to validate catalogValidationValues.json.template file
terraform-ibm-modules/common-dev-assets pull request #961
Opened 2024-05-08 10:16 UTC by akocbek

### Description

Pre-commit hook to validate `catalogValidationValues.json.template` file. Validating:
- is correct JSON file
- are catalog keys part of terraform inputs of the same directory
 
<img width="933" alt="image" src="https://github.com/terraform-ibm-modules/common-dev-assets/assets/106765658/6c7004ed-9e57-4e9b-8955-23f381d430fa">

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-05-08 10:28 UTC, ocofaigh requested changes
wow very powerful linter, I like it - a few comments

2024-05-08 10:28 UTC, ocofaigh commented on module-assets/ci/validateCatalogTemplate.py
> +for root, dirs, files in os.walk("solutions"):
`catalogValidationValues.json.template` can exist in other folders too. Its not consistent, nor will it ever be as its not mandated to place the code in any specific place. Your going to have to check the full repo

2024-05-08 10:28 UTC, ocofaigh commented on module-assets/ci/validateCatalogTemplate.py
> +def create_temp_catalog(root, file):
create_temp_catalog -> create_temp_json

2024-05-08 10:28 UTC, ocofaigh commented on module-assets/.pre-commit-config.yaml
> +    - id: validate_catalog
json_template_lint

2024-05-08 10:28 UTC, ocofaigh commented on module-assets/ci/validateCatalogTemplate.py
> +                        os.path.join(root, file) + " is not valid JSON file."
is not valid JSON file -> is not valid JSON format

2024-05-08 10:28 UTC, ocofaigh commented on module-assets/.pre-commit-config.yaml
> +      entry: python3 ci/validateCatalogTemplate.py
validateCatalogTemplate.py -> validateJsonTemplate.py

2024-05-08 10:28 UTC, ocofaigh commented on module-assets/.terraform-docs-config-validate-catalog.yaml
> +formatter: "json"
can you rename the file `module-assets/.terraform-docs-config-validate-json-template.yaml`

2024-05-08 10:28 UTC, ocofaigh commented on module-assets/ci/validateCatalogTemplate.py
> +                f"Catalog key '{catalog_key}' in '{temp_catalog_file}' is not part of \"{root}\" tf inputs."
Its not a catalog key, its an input variable. Perhaps just say `"Key '{catalog_key}' in ...."`

2024-05-08 10:54 UTC, akocbek commented
searching for `catalogValidationValues.json.template` in all dirs

<img width="1021" alt="image" src="https://github.com/terraform-ibm-modules/common-dev-assets/assets/106765658/8666efed-b5ee-44d7-9392-f83fc50775c5">

2024-05-08 10:54 UTC, akocbek commented on module-assets/ci/validateCatalogTemplate.py
> +for root, dirs, files in os.walk("solutions"):
fixed

2024-05-08 10:54 UTC, akocbek commented on module-assets/ci/validateCatalogTemplate.py
> +def create_temp_catalog(root, file):
fixed

2024-05-08 10:54 UTC, akocbek commented on module-assets/.pre-commit-config.yaml
> +    - id: validate_catalog
fixed

2024-05-08 10:55 UTC, akocbek commented on module-assets/ci/validateCatalogTemplate.py
> +                        os.path.join(root, file) + " is not valid JSON file."
fixed

2024-05-08 10:55 UTC, akocbek commented on module-assets/.pre-commit-config.yaml
> +      entry: python3 ci/validateCatalogTemplate.py
fixed

2024-05-08 10:55 UTC, akocbek commented on module-assets/.terraform-docs-config-validate-catalog.yaml
> +formatter: "json"
fixed

2024-05-08 10:55 UTC, akocbek commented on module-assets/ci/validateCatalogTemplate.py
> +                f"Catalog key '{catalog_key}' in '{temp_catalog_file}' is not part of \"{root}\" tf inputs."
fixed

2024-05-08 11:47 UTC, ocofaigh commented on module-assets/ci/validateJsonTemplate.py
> +                f"Key '{catalog_template_key}' in '{temp_catalog_template_file}' is not part of \"{root}\" tf inputs."
ok looking at the sceenshot you added, maybe lets reword so it displays like:

'var1' defined in 'solutions/standard/catalogValidationValues.json.template' is not a valid input variable for the terraform in this directory.

Also please be aware that you are currently outputting the the value of `temp_catalog_template_file` which is actually the temp file name, so I don't suggest you include that in the output

```suggestion
                f"'{catalog_template_key}' defined in '{temp_catalog_template_file}' is not part of \"{root}\" tf inputs."
```

2024-05-08 14:03 UTC, ocofaigh commented on module-assets/ci/validateJsonTemplate.py
> +                f"Key '{catalog_template_key}' defined in '{temp_catalog_template_file}' is not part of \"{root}\" tf inputs."
Your still printing `temp_catalog_template_file` which is going to be called `temp_catalogValidationValues.json.template` which may cause confusion.

2024-05-08 14:20 UTC, akocbek commented on module-assets/ci/validateJsonTemplate.py
> +                f"Key '{catalog_template_key}' defined in '{temp_catalog_template_file}' is not part of \"{root}\" tf inputs."
oh I missed that one, fixed now

2024-05-08 14:21 UTC, ocofaigh commented
@akocbek Looks good, got a screenshot of final output?

2024-05-10 12:33 UTC, akocbek commented
the latest output when hook fails
<img width="1050" alt="image" src="https://github.com/terraform-ibm-modules/common-dev-assets/assets/106765658/ee7b1f44-f3e9-4aef-b83c-435cfbc5102b">

2024-05-13 17:33 UTC, ocofaigh commented
@akocbek The output in screenshot looks odd, specifically this line: 
`./solutions/standard copy/catalogValidationValues.json.template is not valid JSON format`

Should it not read: `./solutions/standard/catalogValidationValues.json.template is not valid JSON format`

2024-05-14 08:56 UTC, ocofaigh approved these changes

2024-05-14 08:57 UTC, merged